version: '3'

services:
  mysql:
    image: mysql:8.0.11
    container_name: mysql
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
       - ./team4-db/mysql:/usr/src/mysql


volumes:
  team4-db: