# Generated by Django 4.2.3 on 2024-05-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizId', models.AutoField(primary_key=True, serialize=False)),
                ('quizTitle', models.CharField(max_length=200)),
                ('correctAnswer', models.CharField(max_length=150)),
                ('solution', models.CharField(max_length=500)),
            ],
        ),
    ]
