# Generated by Django 5.0.6 on 2024-05-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("quizId", models.AutoField(primary_key=True, serialize=False)),
                ("quizTitle", models.CharField(max_length=200)),
                ("correctAnswer", models.CharField(max_length=150)),
                ("solution", models.CharField(max_length=500)),
            ],
        ),
    ]
